# Generated by Django 6.0.1 on 2026-01-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
