# Generated by Django 6.0.3 on 2026-03-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product'),
        ),
    ]
