name: CI/CD Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test Cloudinary Connection
        run: |
          docker build -t backend-test ./backend
            
          docker run --rm \
            -e CLOUDINARY_NAME="${{ secrets.CLOUDINARY_NAME }}" \
            -e CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}" \
            -e CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}" \
            -e FORCE_SEED="True" \
            -e PYTHONPATH="/app" \
            backend-test sh -c "python manage.py migrate && python ecommerce/scripts/seed_products.py"

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend Test
        run: |
          cd frontend
          npm run build

  deploy:
    needs: [test-backend, test-frontend] 
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deploy
        run: curl ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}
        
      - name: Trigger Frontend Deploy
        run: curl ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}